title: "Headers"
description: |
  Headers are used to break up content.

patterns:
  banner:
    fields:
      - name: heading
        type: string
        example: "Skinful"
      - name: text
        type: string
        example: "Clean skincare for beautiful skin"
